### ISSUE TITLE
The testing fail start from create cluster

### ISSUE THREAD

**Issue by ghost** [93i7xo2/HASS#3]
Check all of the nodes is down or not

**Comment by 93i7xo2** [comment]
All node are alive. Start building again.
---
Building failed. 
---

**Comment by mohwildanhabibi** [comment]
It happens because the controller shutted down or rebooted by itself, so the testing machine's session in login in openstack dashboard is gone, and it not meet our testing precondition. So i decided to modify the KORAT's test case to do log in and log out in openstack dashboard.
